BEGIN;

CREATE TABLE IF NOT EXISTS udp_cubiculos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(64) NOT NULL,
    estado VARCHAR(16) NOT NULL DEFAULT 'disponible',
    creado TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modificado TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estatus CHAR(1) NOT NULL DEFAULT 'A',
    CONSTRAINT ck_udp_cubiculos_estado CHECK (estado IN ('disponible', 'ocupado'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_udp_cubiculos_nombre
    ON udp_cubiculos (nombre);

ALTER TABLE udp_atenciones
    ADD COLUMN IF NOT EXISTS id_cubiculo INTEGER;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_udp_atenciones_cubiculo'
          AND conrelid = 'udp_atenciones'::regclass
    ) THEN
        ALTER TABLE udp_atenciones
            ADD CONSTRAINT fk_udp_atenciones_cubiculo
            FOREIGN KEY (id_cubiculo) REFERENCES udp_cubiculos (id);
    END IF;
END;
$$;

CREATE INDEX IF NOT EXISTS ix_udp_atenciones_id_cubiculo
    ON udp_atenciones (id_cubiculo);

COMMIT;
